### ISSUE TITLE
N64 Compatibility

### ISSUE THREAD

**Issue by austinkelleher** [andrejewski/identity#1]
I'm looking to use this library as the background on my N64 dashboard. The issue is that the N64 does not support dashboards. How can I fix this? Thanks in advance.

/cc @wenkesj @charlieduong94 @druotic

**Comment by areese159** [comment]
I was also hoping to use this library but not on the N64. Could we make this available on GameCube as well?

**Comment by areese159** [comment]
I think this would benefit @charliedoung94 as well.

**Comment by ctdio** [comment]
A Switch port would be ideal for me.

**Comment by Epitrochoid** [comment]
I attempted to load this onto my Ti-83 graphing calculator as a background, but I was unable to attach it to my computer with either a USB-A or Type-C connector. Would you please send me the correct cable to properly load the image onto my calculator?

**Comment by andrejewski** [comment]
@austinkelleher @areese159 @charlieduong94 This project cannot support any Nintendo hardware due to them doing everything they can to prevent [SM64 Online](https://www.youtube.com/watch?v=YS3CrLG8dEg).

@Epitrochoid Ti-80+ calculators include support by default. To enable it, set all variables to the cosine fixed point. You should see the below:

![imageedit_1_6391732528](https://user-images.githubusercontent.com/1660953/34993354-0dd67678-fa9e-11e7-8ad2-60bc15bd1b78.png)

Closing as this question was too good and I actively discourage meaningful discussion.
